author:
  email: emma.fackelmann@gmail.com
  name: Emma Fackelmann
# baseURL: https://everybodystalkingtherapy.github.io/website
baseURL: https://www.everybodystalkingtherapy.ca
copyright: COPYRIGHT © 2023 EVERYBODY'S TALKING THERAPY - ALL RIGHTS RES.
languageCode: en-us
title: Everybody’s Talking Psychotherapy Services 
theme: paige
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
menu:
  main:
  - identifier: home
    name: Home
    weight: 10
    url: /
  - identifier: about
    name: About
    weight: 20
    url: /about/
  - identifier: booking_and_fees
    name: Booking and Fees
    weight: 30
    url: /booking_and_fees/
  - identifier: starting_therapy
    name: Starting Therapy
    weight: 40
    url: /starting_therapy/
  - identifier: in_a_crisis
    name: In a Crisis
    weight: 50
    url: /in_a_crisis/
  - identifier: resources_in_a_pinch
    name: Resources In a Pinch
    weight: 50
    url: /resources_in_a_pinch/
social:
  envelope: mailto:emma.fackelmann@gmail.com